baseURL = "https://sakhawathsumit.github.io/"
languageCode = "en-us"
title = "Sakhawat H Sumit"
theme = "hugo-noir"
# URL handling
relativeURLs = true
canonifyURLs = true

[params]
  customCSS = ["css/custom.css"]  
  name = "Sakhawat H Sumit"
  profile_image = "/images/profile.jpg"
  location = "Saarbrücken, Germany"

  description = """
  I am currently writing my Master's thesis and 
  expect to graduate by the summer of 2026.

  My primary research ambition is to design efficient neural network models 
  that learn abstract representations of structural composition, 
  ensuring that the reasoning behind the compositional process remains 
  tractable and rigorously interpretable.

  To this end, I leverage Group Representation Theory to unify these concepts 
  within a formal framework.
  Currently, I am deepening my understanding of Group Representation Theory 
  and expanding my knowledge into Category Theory.
  """

  linkedin = "https://linkedin.com/in/sakhawathsumit"
  email = "xshsumit@gmail.com"
  logo = "/images/s.ico"


# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 5

[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 1

  [[menu.main]]
    name = "Research"
    pageRef = "/research"
    weight = 2

